apiVersion: v1
kind: Pod
metadata:
  name: curl-monitor
  namespace: monitoring
  labels:
    role: monitor
spec:
  containers:
  - name: curl
    image: curlimages/curl:8.6.0
    command: ["sleep", "3600"]