# postgres-headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None   # Headless service
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432