apiVersion: v1
kind: Pod
metadata:
  name: nginx-ok
  namespace: team-alpha
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 3
        memory: 512Mi
      limits:
        cpu: 5
        memory: 1Gi