apiVersion: v1
kind: Pod
metadata:
  name: curl-frontend
  namespace: frontend
  labels:
    role: client
spec:
  containers:
  - name: curl
    image: curlimages/curl:8.6.0
    command: ["sleep", "3600"]